matching_groups:
  - /users/transaction\.json
  - /users/.+\.json
  - /upload/.+\.jpg
  - /items/.+\.json
  - /transactions/.+\.png
  - /static/*
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.ndjson
